export const PAYMENT_PROCESS_REQUEST = 'PAYMENT_PROCESS_REQUEST'
export const PAYMENT_PROCESS_SUCCESS = 'PAYMENT_PROCESS_SUCCESS'
export const PAYMENT_PROCESS_FAIL = 'PAYMENT_PROCESS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'